apiVersion: v1
kind: Pod
metadata:
  name: motis
spec:
  securityContext:
    fsGroup: 1000
  containers:
  - name: motis
    image: ghcr.io/motis-project/motis:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data-volume
      mountPath: /data
    - name: input-volume
      mountPath: /input
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: motis-data-pvc
  - name: input-volume
    persistentVolumeClaim:
      claimName: motis-input-pvc
