# permissions for end users to edit datasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataset-editor-role
rules:
- apiGroups:
  - motis.motis-project.de
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - motis.motis-project.de
  resources:
  - datasets/status
  verbs:
  - get
