# permissions for end users to view datasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataset-viewer-role
rules:
- apiGroups:
  - motis.motis-project.de
  resources:
  - datasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - motis.motis-project.de
  resources:
  - datasets/status
  verbs:
  - get
