# permissions for end users to view motis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: motis-viewer-role
rules:
- apiGroups:
  - motis.motis-project.de
  resources:
  - motis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - motis.motis-project.de
  resources:
  - motis/status
  verbs:
  - get
