# Modified version of: https://stackoverflow.com/a/70323207/7373663
# Which is licensed under: https://creativecommons.org/licenses/by-sa/4.0/
apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
    - name: pvc-inspector
      image: busybox
      command: ["tail"]
      args: ["-f", "/dev/null"]
      volumeMounts:
        - mountPath: /pvc
          name: pvc-mount
  volumes:
    - name: pvc-mount
      persistentVolumeClaim:
        claimName: motis-input-pvc